FROM node:alpine
WORKDIR '/app'
COPY ./package.json ./
RUN npm install

COPY ./config ./config
COPY ./prisma ./prisma
COPY ./src ./src
COPY ./codegen.yml ./codegen.yml
COPY ./.graphqlconfig ./.graphqlconfig
COPY ./tsconfig.json ./tsconfig.json

# RUN npm run generate
RUN npm run build
CMD [ "npm", "run", "start" ]